# .github/config.yml
# Welcome Bot configuration for IO Beats ğŸ¶

# Message when someone opens their first issue
newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first *issue* on **IO Beats**!  
  The team will review it shortly.  
  ğŸ‘‰ Check out our [Wiki](https://github.com/iobeatss/treasury/wiki)  
  ğŸ‘‰ Join our community on [Telegram](https://t.me/iobeats) / [Discord](https://discord.gg/iobeats)

# Message when someone opens their first PR
newPRWelcomeComment: >
  ğŸš€ Thanks for submitting your first *pull request* to **IO Beats**!  
  We really appreciate your contribution ğŸ™Œ  
  ğŸ‘‰ Please make sure to check our [CONTRIBUTING.md](./CONTRIBUTING.md)

# Message when someone gets their first PR merged
firstPRMergeComment: >
  ğŸ‰ Congratulations! Your first *pull request* has been merged!  
  Thank you for contributing to **IO Beats** â¤ï¸  
  ğŸ‘‰ *One team, one dream.*
